name: Hello World

on:
  pull_request:
    types: [ opened, labeled, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add changed files to PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shopt -s nocasematch
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            if [[ "$file" =~ ".*\.sql" ]]; then
              content="$(cat $file)"
              if [[ "$content" =~ "insert into " ]] || [[ "$content" =~ "update " ]]; then
                echo ":mega: 注意 sqlをdev1環境でEXPLAIN ANALYZEで実行し処理が遅くないか確認して下さい。 :mega:" > ./comment
                gh pr comment ${{ github.event.pull_request.number }} -F ./comment --repo ${{ github.repository }}
                exit 1
              fi
            fi
          done