name: Hello World

on:
  pull_request:
    types: [ opened, labeled, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Add changed files to PR comment
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shopt -s nocasematch
          CHANGES="$(gh pr diff ${{ github.event.pull_request.number }} --repo ${{ github.repository }})"
          echo "$CHANGES"
          if [[ ! "$CHANGES" =~ "insert into " ]]; then
            exit 0
          fi

          echo ":mega: 注意注意 :mega:" > ./comment
          gh pr comment ${{ github.event.pull_request.number }} -F ./comment --repo ${{ github.repository }}
