name: Hello World

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get changed files in migration directories
        id: changed-files
        uses: tj-actions/changed-files@v36
        with:
          files: |
            src/*.sql
      - name: Add changed files to PR comment
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          shopt -s nocasematch
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file"
            content="$(cat $file)"
            if [[ "$content" =~ "insert into " ]] || [[ "$content" =~ "update " ]]; then
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `このプルリクエストにはINSERT/UPDATE文が含まれています。以下のチェックリストを確認して下さい。

                  チェックリスト
                  * [ ] dev1でEXPLAIN ANALYZEを実行し処理が遅くないか(10sec以上)確認した.

                `.replace(/\n +/g, '\n')
              })
              exit 0
            fi
          done