name: Hello World

on:
  pull_request:
    types: [ opened, labeled, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        run: |
          git diff main...HEAD --name-only

      - name: Add changed files to PR comment
        run: |
          shopt -s nocasematch
          CHANGES="$(gh pr diff ${{ github.event.pull_request.number }} --repo ${{ github.repository }})"
          if [[ "$CHANGES" =~ "insert into " ]]; then
            cat << EOF > ./comment
              :mega: 注意注意 :mega:
            EOF
            gh pr comment ${{ github.event.pull_request.number }} -F ./comment --repo ${{ github.repository }}
          fi
